// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	models "arc/models"

	mock "github.com/stretchr/testify/mock"
)

// UserRepositoryDomain is an autogenerated mock type for the UserRepositoryDomain type
type UserRepositoryDomain struct {
	mock.Mock
}

// CreateUsers provides a mock function with given fields: user
func (_m *UserRepositoryDomain) CreateUsers(user models.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUsers provides a mock function with given fields:
func (_m *UserRepositoryDomain) GetUsers() []models.User {
	ret := _m.Called()

	var r0 []models.User
	if rf, ok := ret.Get(0).(func() []models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	return r0
}

// Verify provides a mock function with given fields: email
func (_m *UserRepositoryDomain) Verify(email string) (models.User, error) {
	ret := _m.Called(email)

	var r0 models.User
	if rf, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
