name: ci and cd
on:
  push:
    branches:
      - "main"
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run:  go test -v ./...
  redeploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: denny16/golang:latest

      - name: connect to aws then redeploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop golang
            docker container rm golang
            docker pull denny16/golang:latest
            docker run -e DB_HOST="db-denny.c7ugyajmx0f4.us-east-1.rds.amazonaws.com" -e DB_PASSWORD="rootroot" -p 80:8080 --name golang --detach denny16/golang:latest